<#
  make-server-config.ps1 - create api/config.local.php ON THE SERVER and upload it.

  This file is deliberately excluded from deploy.ps1: it holds the database
  password, the JWT signing key, and the Anthropic API key, and the server's copy
  differs from the local one (the server reaches MySQL over localhost, not over
  the public internet).

  Run this ONCE per environment, and again only to rotate a key. Re-running
  generates a NEW JWT signing key, which invalidates every issued token and logs
  everyone out — pass -KeepJwt to preserve the current one.

  The Anthropic key is read from the local api/config.local.php by default, so it
  never appears on a command line, in shell history, or in a transcript.

  Usage:
    ./scripts/make-server-config.ps1 -DryRun
    ./scripts/make-server-config.ps1
    ./scripts/make-server-config.ps1 -AnthropicKey 'sk-ant-...'   # override
#>
param(
  [string]$AnthropicKey,
  [string]$JwtSecret,
  [int]$DailyMessageLimit = 80,
  [int]$MonthlyBudgetThb = 3000,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

if (-not $AnthropicKey) {
  $localConfig = Join-Path (Split-Path -Parent $PSScriptRoot) 'api\config.local.php'
  if (-not (Test-Path $localConfig)) {
    throw "no -AnthropicKey given and $localConfig does not exist"
  }
  $match = Select-String -Path $localConfig -Pattern "'anthropic_key'\s*=>\s*'([^']+)'"
  if (-not $match) {
    throw "anthropic_key is empty in api/config.local.php - set it there or pass -AnthropicKey"
  }
  $AnthropicKey = $match.Matches[0].Groups[1].Value
  Write-Host "==> using the Anthropic key from api/config.local.php" -ForegroundColor DarkGray
}

$secret = 'D:\SevenSmile\WebSevenSmile\contactrate-web-sevensmile\deploy.secret.ps1'
if (-not (Test-Path $secret)) { throw "credentials not found: $secret" }
. $secret

if (-not $JwtSecret) {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $JwtSecret = ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''
  Write-Host "==> generated a new JWT signing key (all existing sessions will be logged out)" -ForegroundColor Yellow
}

# On the server, MySQL is reachable on localhost — never over the public IP.
$php = @"
<?php
// Generated by scripts/make-server-config.ps1 for ai.sevensmiletourandticket.com.
// Never committed; never overwritten by deploy.ps1.

return [
    'db' => [
        'host' => 'localhost',
        'port' => 3306,
        'name' => '$DbName',
        'user' => '$DbUser',
        'pass' => '$DbPass',
    ],

    'jwt_secret' => '$JwtSecret',

    'anthropic_key' => '$AnthropicKey',

    // Spending guards. Edit these on the server to raise a cap — it takes
    // effect on the next request and survives every deploy, because this file
    // is the one deploy.ps1 never overwrites.
    'limits' => [
        'daily_message_limit' => $DailyMessageLimit,
        'monthly_budget_thb'  => $MonthlyBudgetThb,
    ],

    'allowed_origins' => [
        'https://ai.sevensmiletourandticket.com',
    ],
];
"@

# Write via a temp file so the secret never appears on a command line.
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("nova-config-" + [guid]::NewGuid().ToString('N') + '.php')
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($tmp, $php, $utf8NoBom)

$remote = '/ai.sevensmiletourandticket.com/api/config.local.php'
Write-Host "==> ftp://$DeployHost$remote  $(if ($DryRun) { '[DRY RUN]' })" -ForegroundColor Cyan

try {
  if ($DryRun) {
    Write-Host "  would upload $((Get-Item $tmp).Length) bytes (secrets redacted from this output)" -ForegroundColor DarkGray
  } else {
    $req = [System.Net.FtpWebRequest]::Create("ftp://$DeployHost" + $remote)
    $req.Credentials = New-Object System.Net.NetworkCredential($DeployUser, $DeployPassword)
    $req.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile
    $req.UsePassive = $true; $req.UseBinary = $true; $req.KeepAlive = $false; $req.Timeout = 60000

    $bytes = [System.IO.File]::ReadAllBytes($tmp)
    $req.ContentLength = $bytes.Length
    $stream = $req.GetRequestStream()
    $stream.Write($bytes, 0, $bytes.Length)
    $stream.Close()
    $resp = $req.GetResponse(); $resp.Close()

    Write-Host "  uploaded" -ForegroundColor Green
  }
} finally {
  Remove-Item $tmp -Force -ErrorAction SilentlyContinue
}
