<#
  setup-local-config.ps1 - generate api/config.local.php for local development.

  Pulls the database credentials from the main repo's gitignored deploy.secret.ps1
  and generates a fresh random JWT signing key. The output file is gitignored.

  Existing files are never overwritten without -Force, so a real anthropic_key
  already filled in cannot be lost by re-running this.
#>
param(
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

$target = Join-Path (Split-Path -Parent $PSScriptRoot) 'api\config.local.php'
if ((Test-Path $target) -and -not $Force) {
  Write-Host "already exists: $target (use -Force to regenerate)" -ForegroundColor Yellow
  exit 0
}

$secret = 'D:\SevenSmile\WebSevenSmile\contactrate-web-sevensmile\deploy.secret.ps1'
if (-not (Test-Path $secret)) { throw "credentials not found: $secret" }
. $secret

$bytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$jwt = ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''

$php = @"
<?php
// Generated by scripts/setup-local-config.ps1 - gitignored, do not commit.

return [
    'db' => [
        'host' => '$DbHost',
        'port' => $DbPort,
        'name' => '$DbName',
        'user' => '$DbUser',
        'pass' => '$DbPass',
    ],

    'jwt_secret' => '$jwt',

    // Fill in when the assistant endpoint lands (phase 2).
    'anthropic_key' => '',

    'allowed_origins' => [
        'https://ai.sevensmiletourandticket.com',
        'http://localhost:5173',
        'http://localhost:5174',
    ],
];
"@

# WriteAllText with a plain UTF8Encoding($false) — Set-Content -Encoding utf8 emits a
# BOM on PowerShell 5.1, and a BOM before <?php is echoed straight into the response,
# corrupting every JSON body the API returns.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($target, $php, $utf8NoBom)
Write-Host "wrote $target" -ForegroundColor Green
